version: '3'
services:

  mysqldb:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
      MYSQL_PASSWORD: kemane
      MYSQL_ROOT_PASSWORD: kemane
      MYSQL_DATABASE: crud
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-backend:
    image: lugar2020/backend
    restart: always
    ports:
     - 8020:8020
    depends_on:
     - mysqldb
    links:
     - mysqldb

  react-frontend:
    image: lugar2020/frontend
    restart: always
    ports:
     - 3000:3000
    stdin_open: true
    depends_on:
     - springboot-backend
    links:
     - springboot-backend

volumes:
  mysql-data: